image: python

stages:
  - build
  - test

build:
  stage: build 
  script:
    - pip install -U pip
    - pip install -e .

test:
  stage: test
  before_script:
    - pip install pytest
  script:
    - py.test 