name: CI tests

on:
  pull_request:
  push:
    branches:
    - master
  workflow_dispatch:

# Cancel running workflows when additional changes are pushed
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-a-fallback-value
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:

  pytest:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:3
        ports:
        - 27017:27017

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U setuptools wheel
        pip install -e .[test]

    - name: Run tests
      run: pytest -rs -vvv tests/
